### ISSUE TITLE
[Error] NovetusCMD when NovetusCMD.exe -3d or -no3d with -outputinfo generates a serverinfo file with a invalid novetusurl see in desc 

### ISSUE THREAD

**Issue by LeontKing2** [Novetus/Novetus_src#35]
![image](https://user-images.githubusercontent.com/84083235/146519668-6ecd213a-42f0-4a57-b71c-963b92791095.png)
Not sure if this bug or not

**Comment by LeontKing2** [comment]
Log of CMD ```2021-12-17 14:19:47.5951|INFO|GlobalFuncs|NovetusCMD version 1.3 Pre-Release 5 loaded.
2021-12-17 14:19:47.6190|INFO|GlobalFuncs|Novetus path: C:\\Users\\abhia\\Downloads\\novetus-windows-beta
2021-12-17 14:19:47.6190|WARN|GlobalFuncs|NovetusCMD is now loading main server configurations from the INI file.
2021-12-17 14:19:47.6401|INFO|GlobalFuncs|Config loaded.
2021-12-17 14:19:47.6486|INFO|GlobalFuncs|Client '2011M' successfully loaded.
2021-12-17 14:19:47.6656|ERROR|GlobalFuncs|EXCEPTION|MESSAGE: Root element is missing.
2021-12-17 14:19:47.6656|ERROR|GlobalFuncs|EXCEPTION|STACK TRACE:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at GlobalFuncs.ApplyClientSettings(ClientInfo info, String ClientName, Int32 GraphicsMode, Int32 MeshDetail, Int32 ShadingQuality, Int32 MaterialQuality, Int32 AA, Int32 AASamples, Int32 Bevels, Int32 Shadows_2008, Boolean Shadows_2007, String Style_2007, Int32 GFXQualityLevel, String WindowResolution, String FullscreenResolution, Int32 ModernResolution, Boolean onlyGraphicsMode)
2021-12-17 14:19:47.6656|ERROR|GlobalFuncs|EXCEPTION|ADDITIONAL INFO: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at GlobalFuncs.ApplyClientSettings(ClientInfo info, String ClientName, Int32 GraphicsMode, Int32 MeshDetail, Int32 ShadingQuality, Int32 MaterialQuality, Int32 AA, Int32 AASamples, Int32 Bevels, Int32 Shadows_2008, Boolean Shadows_2007, String Style_2007, Int32 GFXQualityLevel, String WindowResolution, String FullscreenResolution, Int32 ModernResolution, Boolean onlyGraphicsMode)
2021-12-17 14:19:47.6656|INFO|GlobalFuncs|NovetusCMD will launch the server with the default map.
2021-12-17 14:19:47.6656|INFO|GlobalFuncs|NovetusCMD will launch the server with the default client.
2021-12-17 14:19:47.6656|INFO|GlobalFuncs|Launching a 2011M server on Definetlynotcopyofstrgame.rbxl with 12 players.
2021-12-17 14:19:47.6896|ERROR|GlobalFuncs|EXCEPTION|MESSAGE: Root element is missing.
2021-12-17 14:19:47.6896|ERROR|GlobalFuncs|EXCEPTION|STACK TRACE:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at GlobalFuncs.ApplyClientSettings(ClientInfo info, String ClientName, Int32 GraphicsMode, Int32 MeshDetail, Int32 ShadingQuality, Int32 MaterialQuality, Int32 AA, Int32 AASamples, Int32 Bevels, Int32 Shadows_2008, Boolean Shadows_2007, String Style_2007, Int32 GFXQualityLevel, String WindowResolution, String FullscreenResolution, Int32 ModernResolution, Boolean onlyGraphicsMode)
2021-12-17 14:19:47.6896|ERROR|GlobalFuncs|EXCEPTION|ADDITIONAL INFO: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at GlobalFuncs.ApplyClientSettings(ClientInfo info, String ClientName, Int32 GraphicsMode, Int32 MeshDetail, Int32 ShadingQuality, Int32 MaterialQuality, Int32 AA, Int32 AASamples, Int32 Bevels, Int32 Shadows_2008, Boolean Shadows_2007, String Style_2007, Int32 GFXQualityLevel, String WindowResolution, String FullscreenResolution, Int32 ModernResolution, Boolean onlyGraphicsMode)

**Comment by Bitl** [comment]
This was fixed in the main 1.3 release.

**Comment by LeontKing2** [comment]
> This was fixed in the main 1.3 release.

any way to fix this without like editing the source code for 1.3 prerelease 5
